config/routes.rb
Web2print::Application.routes.draw do
  devise_for :users

    scope module: 'frontend' do
      root to: 'home#index'
    end
    scope module: 'app' do
      resources :businesscards, only: [:index]
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/app/application_controller.rb
class App::ApplicationController < ApplicationController
  layout 'backend_application'
  before_filter :authenticate!

  protected
  def authenticate!
    authenticate_or_request_with_http_basic do |username, password|
      username == 'foo' && password == 'moo'
    end
  end
end

app/controllers/app/businesscards_controller.rb
class App::BusinesscardsController < App::ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ApplicationController
  layout 'frontend_application'
end

app/controllers/frontend/home_controller.rb
class Frontend::HomeController < Frontend::ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/businesscards/index.html.erb
<h2> Los Geht's </h2>
<h3> Wählen Sie eine Vorlage aus : </h3>

<div class='template_area'>

</div>

<div class='businesscard' id='template' style='display: none; height:200px; width: 300px; outline:2px solid black; float: left; margin-left:20px; margin-top: 20px'>
</div>

<script type="text/javascript">
jQuery(function($){
  var COLORS = [{hex: '#000000', name: "black"}, {hex:'#FF0000', name: "red"}, {hex:'#32CD32', name: "green"}, {hex: '#EE7600',name: 'orange'}, {hex: '#8B4513',name: 'brown' }, {hex: '#1874CD',name: 'blue'}, {hex:'#8A2BE2', name: 'purple'},{hex: '#D02090',name: 'pink'}, {hex: '#00F5FF', name: 'mint'}];

  $.each(COLORS, function(index, color){
    var template = $('.businesscard[id="template"]').clone();
    template.attr('id', color.hex);
    template.css('background-color', color.hex);
    template.appendTo($('.template_area'));
    template.show();
  });

  $(document).on('click', '.businesscard', function(){
    var color = $(this).attr('id');
    alert('your template got the color: ' + color);
  });
})
</script>

app/views/frontend/home/index.html.erb
<h1>WELCOME TO WEB2PRINT</h1>
<p>
  Willkommen bei Web2Print pi pa po...

app/views/layouts/_menubar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <%= link_to "WEB2PRINT", root_path, :class => "brand" %> 
    <ul class="nav">
      <li><%= link_to "Los geht's", businesscards_path %></li> 
      <li><a href="#">Impressum</a></li> 
    </ul>
  </div>
</div>

app/views/layouts/backend_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web2print</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "app/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/menubar' %>
<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/frontend_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web2print</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "frontend/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/menubar" %>
<%= yield %>

</body>
</html>